version: '2'
services:
  lykkeninjabalancejob:
    image: lykkedev/lykkeninjabalancejob:dev
    container_name: lykkeninjabalancejob
    environment:
      - SettingsUrl=${SettingsUrl}
   

networks:
  mynet:
    driver: bridge
