version: '2'

services:
  lykkeninjaweb:
    image: lykkedev/lykkeninjaweb:dev
    container_name: lykkeninjaweb
    environment:
      - SettingsUrl={SettingsUrl}   
    ports:
      - "${Port}:5000"
    networks:
      - commondockernet

networks:
  commondockernet:
    external: true
